name: CustomArrow-BreakerSpawner
version: '${project.version}'
main: fr.kenda.customarrowbreakerspawner.CustomArrowBreakerSpawner
authors: [Kenda]
description: Plugin pour le client Fiverr ijuju_68
commands:
  givearrow:
    description: Commande pour se give la flèche
